### ISSUE TITLE
HWiNFO support.

### ISSUE THREAD

**Issue by knocks-** [bouteillerAlan/rainmeter-clean-skin#1]
Thanks for creating this great Rainmeter skin, it’s exactly what I’ve been looking for. Did you ever explore moving the plugins to support  HWiNFO?

**Comment by bouteillerAlan** [comment]
Hello thanks :) 

I can, but it needs a little bit of tweaking from the end user if I do : https://docs.rainmeter.net/tips/hwinfo/

I'll try to make it this weekend or next week!

**Comment by knocks-** [comment]
No worries, no need to make it a priority. I was just curious and wanted to say thanks.

**Comment by bouteillerAlan** [comment]
see #2
