### ISSUE TITLE
Flickering on taskbar click

### ISSUE THREAD

**Issue by Nether0ne** [bouteillerAlan/rainmeter-clean-skin#3]
Skin widgets are flickering on taskbar click

Here is a video of the issue:

https://github.com/user-attachments/assets/bb12c651-2638-4642-b49c-e19be25dfa11

At the top left you can see another widget which works just fine in this scenario

**Comment by bouteillerAlan** [comment]
This is very weird :/ 
I cannot reproduce.
The skin is mostly made like the rainmeter doc say to do it.

Can you give me some hint for trying to reproduce ? 
- where is put the widget on your desktop ?
- is this flickering still happening if you change where the widget is placed ?
- what is the taskbar you talk about ? 
- your os ? Window 11 ? Window 10 ?

Thanks :)

**Comment by Nether0ne** [comment]
I'm using Windows 11 Pro 23H2, the widgets work fine when they do not overlay the system's taskbar.

Looks like Windows/Rainmeter conflict ([#1](https://forum.rainmeter.net/viewtopic.php?t=28774), [#2](https://forum.rainmeter.net/viewtopic.php?t=44086)), this happens to all Rainmeter skins, not just yours.
